#!/usr/bin/env bash

THIS_CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Just symlink the whole damn directory
mv /etc/nix-darwin /etc/nix-darwin-bck
ln -s "$THIS_CURRENT_DIR" /etc/nix-darwin
