# Aliases
alias nrs="sudo -i nixos-rebuild switch"
alias nixc="nvim ~/nixos/configuration.nix"
alias dod="cd ~/nixos"

# Environment Variables
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less -S'
export COOKIECUTTER_CONFIG="$HOME/.config/cookiecutter/config.yml"

