on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    name: Build Nix targets
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v4 # This action
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v3
      - name: Lint nix files
        run: nix develop --command alejandra --check .
      - name: Lint bash files
        run: find . -name "*.sh" -print0 | xargs -0 shellcheck --format=gcc
      - name: Lint python with ruff
        run: ruff check .
